### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by likeyoukang** [conesat/HRMS#1]
大神，你好。运行时候报这个错误。debug之后了解到空指针异常，原因是没查到数据。数据库中是有的，怎么野解决不了。你看一下能帮忙解决一下吗？
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.nncq.sunmoon.dao.PowerDao.getAllPowerList
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:196)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:44)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:59)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy42.getAllPowerList(Unknown Source)
	at com.nncq.sunmoon.service.impl.PowerServiceImpl.getAllPowerList(PowerServiceImpl.java:42)
	at com.nncq.sunmoon.controller.GotoJspController.loadSystem(GotoJspController.java:98)

**Comment by xuing** [comment]
```xml
	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.xml</include>
				</includes>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
```
IDEA输出的时候会忽略代码文件夹中的xml文件，POM中中添加上面的代码即可。
叫我雷锋...我也卡了好久...
